homebrew_packages:
  - ansible
  - btop
  - fastfetch
  - git
  - htop
  - jq
  - lazygit
  - neovim
  - nmap
  - packer
  - python3
  - rio-terminal
  - terraform
  - tmux
  - tree
  - wget

homebrew_cask_apps:
  - iterm2
  - spotify
  - visual-studio-code
